# Generated by Django 5.2 on 2025-04-26 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_course_file_alter_course_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
