# Generated by Django 5.2 on 2025-04-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_message_conversation_delete_conversation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.FileField(blank=True, default='default.jpg', max_length=200, null=True, upload_to='course-file'),
        ),
    ]
