# Generated by Django 5.2 on 2025-05-13 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_uses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='api.course'),
        ),
        migrations.AlterField(
            model_name='variantitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.variant'),
        ),
    ]
