# Generated by Django 5.2 on 2025-05-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_coupon_end_date_alter_coupon_max_uses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_uses',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
