# Generated by Django 5.2 on 2025-05-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_userdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese')], default='en', max_length=10),
        ),
    ]
