# Generated by Django 5.2 on 2025-05-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_userdocument_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='study_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
