# Generated by Django 5.2 on 2025-05-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_userdocument_study_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, unique=True)),
                ('normalized_topic', models.CharField(db_index=True, max_length=255)),
                ('field_en', models.CharField(max_length=100)),
                ('field_vi', models.CharField(max_length=100)),
                ('explanation_en', models.TextField(blank=True)),
                ('explanation_vi', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
