# Generated by Django 5.2 on 2025-05-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_approvedtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedtopic',
            name='complexity',
            field=models.CharField(blank=True, default='undergraduate', max_length=50),
        ),
    ]
