# Generated by Django 5.2 on 2025-05-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_approvedtopic_complexity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvedtopic',
            old_name='complexity',
            new_name='complexity_en',
        ),
        migrations.AddField(
            model_name='approvedtopic',
            name='complexity_vi',
            field=models.CharField(blank=True, default='đại học', max_length=50),
        ),
    ]
