# Generated by Django 5.2 on 2025-06-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_complexity_approvedtopic_complexity_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.FileField(blank=True, default='default.png', max_length=200, null=True, upload_to='course-file'),
        ),
    ]
