# Generated by Django 5.2 on 2025-06-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.FileField(blank=True, default='default.jpg', max_length=200, null=True, upload_to='course-file'),
        ),
    ]
