# Generated by Django 5.2 on 2025-05-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_user_refresh_token_alter_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clerk_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
